// Generated by scripts/generate-route-data.ts. Do not edit by hand.
export const validGuidePaths = [
  "/guides/a-coffee-mug-guide",
  "/guides/camping-gear-checklist",
  "/guides/ceramic-coffee-mug-guide",
  "/guides/ceramics-coffee-mug-guide",
  "/guides/coffee-and-mug-guide",
  "/guides/coffee-ceramic-mug-guide",
  "/guides/coffee-coffee-coffee-mug-guide",
  "/guides/coffee-coffee-mug-guide",
  "/guides/coffee-mug-coffee-guide",
  "/guides/coffee-mug-guide",
  "/guides/coffee-with-coffee-mug-guide",
  "/guides/customised-coffee-mug-guide",
  "/guides/home-office-smart-gadgets",
  "/guides/mug-and-coffee-guide",
  "/guides/smart-home-energy-savers",
  "/guides/yoga-mat-near-me-guide"
] as const;
export const validCategories = [
  "Office Setup",
  "Outdoor Gear",
  "Smart Home",
  "Yoga Mats",
  "coffee mug"
] as const;
