// Generated by scripts/generate-route-data.ts. Do not edit by hand.
export const validGuidePaths = [
  "/guides/camping-gear-checklist",
  "/guides/home-office-smart-gadgets",
  "/guides/smart-home-energy-savers"
] as const;
export const validCategories = [
  "Office Setup",
  "Outdoor Gear",
  "Smart Home"
] as const;
