// Generated by scripts/generate-route-data.ts. Do not edit by hand.
export const validPostIds = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17"
] as const;
export const validCategories = [
  "Office Setup",
  "Outdoor Gear",
  "Smart Home"
] as const;
