import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { posts } from '../src/guides';
import { guidePath } from '../src/guides';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../functions/route-data.ts');

const guidePaths = [...new Set(posts.map((post) => guidePath(post.id)))].sort();
const categories = [...new Set(posts.map((post) => post.category))].sort();

const contents = `// Generated by scripts/generate-route-data.ts. Do not edit by hand.
export const validGuidePaths = ${JSON.stringify(guidePaths, null, 2)} as const;
export const validCategories = ${JSON.stringify(categories, null, 2)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, contents);
