import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { posts } from '../src/data/posts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../functions/route-data.ts');

const postIds = [...new Set(posts.map((post) => post.id))].sort((a, b) => Number(a) - Number(b));
const categories = [...new Set(posts.map((post) => post.category))].sort();

const contents = `// Generated by scripts/generate-route-data.ts. Do not edit by hand.
export const validPostIds = ${JSON.stringify(postIds, null, 2)} as const;
export const validCategories = ${JSON.stringify(categories, null, 2)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, contents);
